version: 0.2
phases:
    install:
    runtime-versions:
    nodejs: 14.17.5

    pre_build:
        commands: - echo Installing source NPM dependencies... - npm install --unsafe-perm

    build:
        commands: - echo Build started on `date` - echo Compiling the Node.js code - npm run build

    post_build:
        commands: - echo Build completed on `date` - rm -rf node_modules

artifacts:
    files: - '**/*'